make:
	mkdir build 
	nasm -f win32 src/switch_win.asm -o build/switch_win.o && gcc -o run build/switch_win.o

debug:
	mkdir build
	nasm -g -f win32 src/gdb_debug_win.asm -o build/gdb_debug_win.o && gcc -o run build/gdb_debug_win.o
